using Mutagen.Bethesda;
using Mutagen.Bethesda.Synthesis;
using Mutagen.Bethesda.Fallout4;
using Noggog;

namespace HasDistantLOD
{
    public class Program
    {
        static Lazy<HasDistantLodSettings> _lazySettings = null!;
        static HasDistantLodSettings Settings => _lazySettings.Value; 
        public static async Task<int> Main(string[] args)
        {
            return await SynthesisPipeline.Instance
                .AddPatch<IFallout4Mod, IFallout4ModGetter>(RunPatch)
                .SetAutogeneratedSettings(
                    nickname: "Settings",
                    path: "settings.json",
                    out _lazySettings)
                .SetTypicalOpen(GameRelease.Fallout4, "HasDistantLOD.esp")
                .Run(args);
        }

        public static void RunPatch(IPatcherState<IFallout4Mod, IFallout4ModGetter> state)
        {
            Console.WriteLine("HasDistantLOD START");

            //iterate over all static records
            foreach (var staticGetter in state.LoadOrder.PriorityOrder.Static().WinningOverrides())
            {
                //skip statics that don't have the HasDistantLod flag
                if (!Enums.HasFlag(staticGetter.MajorRecordFlagsRaw, (int)Static.MajorFlag.HasDistantLod)) continue;
                if (staticGetter is null || staticGetter.EditorID is null) continue;
                if (staticGetter.EditorID.Contains("FOLIP_")) continue;

                //add it to the patch
                var myFavoriteStatic = state.PatchMod.Statics.GetOrAddAsOverride(staticGetter);
                
                //remove flag
                myFavoriteStatic.MajorRecordFlagsRaw = Enums.SetFlag(staticGetter.MajorRecordFlagsRaw, (int)Static.MajorFlag.HasDistantLod, false);
                if (Settings.verboseConsoleLog)
                    Console.WriteLine($"Removed HasDistantLOD flag from {staticGetter.EditorID}.");
            }
        }
    }
}
